package bangun;

public class BangunRuang extends javax.swing.JFrame {
    
    Kubus ku;
    Balok blk;
    Bola bl;
    Kerucut kct;
    LimasSegiempat lms;
    PrismaSegitiga pris;
    Tabung tb;
    public BangunRuang() {
        initComponents();
        ku = new Kubus();
        blk = new Balok();
        bl = new Bola();
        kct = new Kerucut();
        lms = new LimasSegiempat();
        pris = new PrismaSegitiga();
        tb = new Tabung();
        
        jPanel1.add(ku);
        jPanel1.add(blk);
        jPanel1.add(bl);
        jPanel1.add(kct);
        jPanel1.add(lms);
        jPanel1.add(pris);
        jPanel1.add(tb);
        
        ku.setVisible(true);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(false);
        pris.setVisible(false);
        tb.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        butKubus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        butBalok = new javax.swing.JButton();
        butLimas = new javax.swing.JButton();
        butBola = new javax.swing.JButton();
        butPrisma = new javax.swing.JButton();
        butKerucut = new javax.swing.JButton();
        butTabung = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Bangun Ruang");

        butKubus.setText("Kubus");
        butKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKubusActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        butBalok.setText("Balok");
        butBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBalokActionPerformed(evt);
            }
        });

        butLimas.setText("Limas Segiempat");
        butLimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimasActionPerformed(evt);
            }
        });

        butBola.setText("Bola");
        butBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBolaActionPerformed(evt);
            }
        });

        butPrisma.setText("Prisma Segitiga");
        butPrisma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butPrismaActionPerformed(evt);
            }
        });

        butKerucut.setText("Kerucut");
        butKerucut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butKerucutActionPerformed(evt);
            }
        });

        butTabung.setText("Tabung");
        butTabung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTabungActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butKubus, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butBalok, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butLimas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butPrisma, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butTabung, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butKerucut, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butBola, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butKubus)
                        .addGap(18, 18, 18)
                        .addComponent(butBalok)
                        .addGap(18, 18, 18)
                        .addComponent(butLimas)
                        .addGap(19, 19, 19)
                        .addComponent(butPrisma)
                        .addGap(18, 18, 18)
                        .addComponent(butTabung)
                        .addGap(18, 18, 18)
                        .addComponent(butKerucut)
                        .addGap(18, 18, 18)
                        .addComponent(butBola)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKubusActionPerformed
        ku.setVisible(true);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(false);
        pris.setVisible(false);
        tb.setVisible(false);
    }//GEN-LAST:event_butKubusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void butBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBalokActionPerformed
        ku.setVisible(false);
        blk.setVisible(true);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(false);
        tb.setVisible(false);
        pris.setVisible(false);
    }//GEN-LAST:event_butBalokActionPerformed

    private void butLimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimasActionPerformed
        ku.setVisible(false);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(true);
        pris.setVisible(false);
        tb.setVisible(false);
    }//GEN-LAST:event_butLimasActionPerformed

    private void butBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBolaActionPerformed
        ku.setVisible(false);
        blk.setVisible(false);
        bl.setVisible(true);
        kct.setVisible(false);
        lms.setVisible(true);
        pris.setVisible(false);
        tb.setVisible(false);
    }//GEN-LAST:event_butBolaActionPerformed

    private void butPrismaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butPrismaActionPerformed
        ku.setVisible(false);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(false);
        pris.setVisible(true);
        tb.setVisible(false);
    }//GEN-LAST:event_butPrismaActionPerformed

    private void butKerucutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butKerucutActionPerformed
        ku.setVisible(false);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(true);
        lms.setVisible(false);
        pris.setVisible(false);
        tb.setVisible(false);
    }//GEN-LAST:event_butKerucutActionPerformed

    private void butTabungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTabungActionPerformed
        ku.setVisible(false);
        blk.setVisible(false);
        bl.setVisible(false);
        kct.setVisible(false);
        lms.setVisible(true);
        pris.setVisible(false);
        tb.setVisible(true);
    }//GEN-LAST:event_butTabungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BangunRuang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BangunRuang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBalok;
    private javax.swing.JButton butBola;
    private javax.swing.JButton butKerucut;
    private javax.swing.JButton butKubus;
    private javax.swing.JButton butLimas;
    private javax.swing.JButton butPrisma;
    private javax.swing.JButton butTabung;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
